Rename workflow

diff --git a/.github/workflows/create-tfstate-s3-bucket.yml b/.github/workflows/create-tfstate-s3-bucket.yml
--- a/.github/workflows/create-tfstate-s3-bucket.yml
+++ b/.github/workflows/create-tfstate-s3-bucket.yml
@@ -76,8 +76,25 @@ jobs:
             terraform plan -no-color -out=tfplan >> $GITHUB_OUTPUT
             echo 'EOF' >> $GITHUB_OUTPUT
         - name: Terraform Plan Status
-          # if: steps.tfplan.outcome == 'failure'
+          if: steps.tfplan.outcome == 'failure'
           run: exit 1
+         # Generates an execution plan for Terraform
+      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+        - name: Terraform Plan
+          id: tf-plan
+          run: |
+           export exitcode=0
+           terraform plan -destroy -var-file=settings/$ENV/variables.tfvars -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+
+           echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+
+           if [ $exitcode -eq 1 ]; then
+             echo Terraform Plan Failed!
+             exit 1
+           else 
+              exit 0
+           fi
+
       
             # On push to "main", build or change infrastructure according to Terraform configuration files
             # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
